// GENERATED CODE -- DO NOT EDIT!

// package: VRAlgorithm
// file: algorithm.proto

import * as algorithm_pb from "./algorithm_pb";
import * as grpc from "@grpc/grpc-js";

interface IAlgorithmService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  serviceStatus: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  checkSelf: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  depthCameraStatus: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  fisheyeCameraStatus: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  closeDepthCamera: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startAposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopAposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startIposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopIposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startScan: grpc.MethodDefinition<algorithm_pb.StartScanReq, algorithm_pb.CommonRes>;
  stopScan: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  cancelScan: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startGestureDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopGestureDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startPersonDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopPersonDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startGestureIposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopGestureIposeDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startAmbientLightDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopAmbientLightDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startShoulderDetect: grpc.MethodDefinition<algorithm_pb.ShoulderDetectReq, algorithm_pb.CommonRes>;
  stopShoulderDetect: grpc.MethodDefinition<algorithm_pb.ShoulderDetectReq, algorithm_pb.CommonRes>;
  startShoulderLegalityDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopShoulderLegalityDetect: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startScanQRCode: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopScanQRCode: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startCameraDormant: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  endCameraDormant: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startHeightMeasurement: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  endHeightMeasurement: grpc.MethodDefinition<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
}

export const AlgorithmService: IAlgorithmService;

export interface IAlgorithmServer extends grpc.UntypedServiceImplementation {
  serviceStatus: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  checkSelf: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  depthCameraStatus: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  fisheyeCameraStatus: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  closeDepthCamera: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startAposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopAposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startIposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopIposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startScan: grpc.handleUnaryCall<algorithm_pb.StartScanReq, algorithm_pb.CommonRes>;
  stopScan: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  cancelScan: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startGestureDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopGestureDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startPersonDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopPersonDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startGestureIposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopGestureIposeDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startAmbientLightDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopAmbientLightDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startShoulderDetect: grpc.handleUnaryCall<algorithm_pb.ShoulderDetectReq, algorithm_pb.CommonRes>;
  stopShoulderDetect: grpc.handleUnaryCall<algorithm_pb.ShoulderDetectReq, algorithm_pb.CommonRes>;
  startShoulderLegalityDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopShoulderLegalityDetect: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startScanQRCode: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  stopScanQRCode: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startCameraDormant: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  endCameraDormant: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  startHeightMeasurement: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
  endHeightMeasurement: grpc.handleUnaryCall<algorithm_pb.CommonReq, algorithm_pb.CommonRes>;
}

export class AlgorithmClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  serviceStatus(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  serviceStatus(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  serviceStatus(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  checkSelf(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  checkSelf(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  checkSelf(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  depthCameraStatus(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  depthCameraStatus(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  depthCameraStatus(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  fisheyeCameraStatus(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  fisheyeCameraStatus(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  fisheyeCameraStatus(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  closeDepthCamera(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  closeDepthCamera(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  closeDepthCamera(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startIposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startIposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startIposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopIposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopIposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopIposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScan(argument: algorithm_pb.StartScanReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScan(argument: algorithm_pb.StartScanReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScan(argument: algorithm_pb.StartScanReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScan(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScan(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScan(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  cancelScan(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  cancelScan(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  cancelScan(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startPersonDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startPersonDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startPersonDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopPersonDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopPersonDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopPersonDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureIposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureIposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startGestureIposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureIposeDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureIposeDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopGestureIposeDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAmbientLightDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAmbientLightDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startAmbientLightDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAmbientLightDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAmbientLightDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopAmbientLightDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderDetect(argument: algorithm_pb.ShoulderDetectReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderLegalityDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderLegalityDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startShoulderLegalityDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderLegalityDetect(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderLegalityDetect(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopShoulderLegalityDetect(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScanQRCode(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScanQRCode(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startScanQRCode(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScanQRCode(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScanQRCode(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  stopScanQRCode(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startCameraDormant(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startCameraDormant(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startCameraDormant(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endCameraDormant(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endCameraDormant(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endCameraDormant(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startHeightMeasurement(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startHeightMeasurement(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  startHeightMeasurement(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endHeightMeasurement(argument: algorithm_pb.CommonReq, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endHeightMeasurement(argument: algorithm_pb.CommonReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
  endHeightMeasurement(argument: algorithm_pb.CommonReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<algorithm_pb.CommonRes>): grpc.ClientUnaryCall;
}
