/*
 * @Description: do something
 * @Author: WendyGao
 * @Date: 2022-02-17 16:36:19
 * @LastEditors: DonWang wangwenqiu@suanier.com
 * @LastEditTime: 2023-08-29 10:40:48
 */

// measure
export const RESTART_STORE = 'RESTART_STORE'
export const CHANGE_SCAN_STATE = 'CHANGE_SCAN_STATE'
export const CHANGE_MEASURE_INFO = 'CHANGE_MEASURE_INFO'
export const CHANGE_REPORT_LIST = 'CHANGE_REPORT_LIST'
export const PUSH_REPORT_LIST = 'PUSH_REPORT_LIST'
export const METE_TITLE = 'METE_TITLE'
export const CHANGE_QRCODE = 'CHANGE_QRCODE'
export const CHANGE_INIT_MESINFO = 'CHANGE_INIT_MESINFO'
// device
export const CHANGE_EXTERNAL = 'CHANGE_EXTERNAL'
export const CHANGE_LIGHT_LEVEL = 'CHANGE_LIGHT_LEVEL'
export const CHANGE_DEVICE_INFO = 'CHANGE_DEVICE_INFO'
export const CHANGE_NET_SPEED_INFO = 'CHANGE_NET_SPEED_INFO'
export const CHANGE_EMERGENCY_STATE = 'CHANGE_EMERGENCY_STATE'
export const ADD_DEVICE_ERROR = 'ADD_DEVICE_ERROR'
export const REMOVE_DEVICE_ERROR = 'REMOVE_DEVICE_ERROR'
export const CHANGE_RECOVERY_STATUS = 'CHANGE_RECOVERY_STATUS'
export const CHANGE_STAND_PEOPLE = 'CHANGE_STAND_PEOPLE'
export const CHANGE_NUMBER = 'CHANGE_NUMBER'
export const CHANGE_UPLOAD_TASK_SUM = 'CHANGE_UPLOAD_TASK_SUM'
export const RESET_DEVICE_ERROR = 'RESET_DEVICE_ERROR'
export const STATUS_CLIENT = 'STATUS_CLIENT'
// service
export const SET_EXT_SERVICES = 'SET_EXT_SERVICES'
export const CHANGE_EXT_SERVICE = 'CHANGE_EXT_SERVICE'

// other
export const CHANGE_OPEN_SHUT_DOEN_VIEW = 'CHANGE_OPEN_SHUT_DOEN_VIEW'
export const CHANGE_PAGE_INFO = 'CHANGE_PAGE_INFO'
export const CHANGE_SETTING_INFO = 'CHANGE_SETTING_INFO'
export const CHANGE_UPDATE_INFO = 'CHANGE_UPDATE_INFO'
